# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EGMSPlugin
                                 A QGIS plugin
 loading and visualizing EGMS Copernicus deformation data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-22
        copyright            : (C) 2026 by Cristina Gonzalez Torres
        email                : id063761@usal.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EGMSPlugin class from file EGMSPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .egms_profile import EGMSPlugin
    return EGMSPlugin(iface)
