# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EGMSPluginDialog
                                 A QGIS plugin
 loading and visualizing EGMS Copernicus deformation data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Cristina Gonzalez Torres
        email                : id063761@usal.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# -*- coding: utf-8 -*-
import os
import csv
import matplotlib.pyplot as plt

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox
from qgis.PyQt.QtCore import QVariant
from qgis.PyQt.QtGui import QColor
from qgis.core import QgsFeatureRequest

from qgis.core import (
    QgsVectorLayer,
    QgsField,
    QgsFeatureRequest,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsProject,
    QgsGraduatedSymbolRenderer,
    QgsRendererRange,
    QgsSymbol,
    QgsWkbTypes,
    Qgis
)

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'egms_profile_dialog_base.ui'))


class EGMSPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        super(EGMSPluginDialog, self).__init__(parent)
        self.setupUi(self)
        self.iface = iface
        self.egms_data = []
        self.layer = None
        self.fig = None
        self.profile_data = []

        self.btn_load.clicked.connect(self.load_csv)
        self.btn_filter.clicked.connect(self.apply_filter)
        self.btn_profile.clicked.connect(self.draw_profile)
        self.btn_export.clicked.connect(self.export)

        self.cmb_layer.layerChanged.connect(self.load_from_layer)

        self.load_from_layer(self.cmb_layer.currentLayer())

    def load_csv(self):
        filepath = self.file_widget.filePath()
        if not filepath:
            self.iface.messageBar().pushMessage(
                "EGMS", "Select a CSV file first", level=Qgis.Warning)
            return

        self.egms_data = []
        try:
            with open(filepath, newline='', encoding='utf-8') as f:
                reader = csv.DictReader(f, delimiter=',')
                for row in reader:
                    self.egms_data.append(row)
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Error reading file: {e}")
            return

        self.create_layer(os.path.splitext(os.path.basename(filepath))[0])
        self.iface.messageBar().pushMessage(
            "EGMS", f"Loaded {len(self.egms_data)} points", level=Qgis.Success)

    def load_from_layer(self, layer):
        """Carga los datos desde una capa vectorial ya existente en QGIS.
        Se activa automáticamente cuando el usuario cambia la capa
        seleccionada en cmb_layer."""
        
        # Si no hay capa seleccionada salimos
        if not layer:
            return
        
        # Solo aceptamos capas vectoriales
        if not isinstance(layer, QgsVectorLayer):
            return
        
        # Solo aceptamos capas de puntos
        if layer.geometryType() != QgsWkbTypes.PointGeometry:
            return

        # Vaciamos los datos anteriores
        self.egms_data = []
        self.layer = layer

        # Obtenemos los nombres de los campos de la capa
        field_names = [field.name() for field in layer.fields()]

        # Iteramos por todas las entidades de la capa
        for feature in layer.getFeatures():
            # Convertimos cada entidad en un diccionario
            row = {}
            for field in field_names:
                row[field] = str(feature[field])
            # Añadimos las coordenadas desde la geometría
            geom = feature.geometry()
            if geom:
                pt = geom.asPoint()
                row['latitude'] = str(pt.y())
                row['longitude'] = str(pt.x())
            self.egms_data.append(row)

        
        print(f"egms_data loaded: {len(self.egms_data)} points")
        self.iface.messageBar().pushMessage(
            "EGMS", f"Layer loaded: {layer.name()} ({len(self.egms_data)} points)",
            level=Qgis.Success)

    def create_layer(self, layer_name):
        self.layer = QgsVectorLayer("Point?crs=EPSG:4326", layer_name, "memory")
        provider = self.layer.dataProvider()

        provider.addAttributes([
            QgsField("pid", QVariant.String),
            QgsField("mean_velocity", QVariant.Double),
            QgsField("rmse_ts", QVariant.Double),
            QgsField("latitude", QVariant.Double),
            QgsField("longitude", QVariant.Double),
        ])
        self.layer.updateFields()

        features = []
        for row in self.egms_data:
            try:
                lat = float(row['latitude'])
                lon = float(row['longitude'])
                vel = float(row['mean_velocity'])
                f = QgsFeature()
                f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(lon, lat)))
                f.setAttributes([row['pid'], vel, float(row['rmse_ts']), lat, lon])
                features.append(f)
            except (ValueError, KeyError):
                continue

        provider.addFeatures(features)
        self.apply_symbology()
        QgsProject.instance().addMapLayer(self.layer)

    def apply_symbology(self):

        colors = [
            (-20, -5, QColor(215, 25, 28)),
            (-5,  -1, QColor(253, 174, 97)),
            (-1,   1, QColor(255, 255, 191)),
            (1,    5, QColor(166, 217, 106)),
            (5,   20, QColor(26, 150, 65)),
        ]

        ranges = []
        for vmin, vmax, color in colors:
            symbol = QgsSymbol.defaultSymbol(self.layer.geometryType())
            symbol.setColor(color)
            symbol.setSize(1.5)
            ranges.append(QgsRendererRange(vmin, vmax, symbol, f"{vmin} to {vmax} mm/yr"))

        renderer = QgsGraduatedSymbolRenderer(velocity_field, ranges)
        self.layer.setRenderer(renderer)
        self.layer.triggerRepaint()

    def apply_filter(self):

        velocity_field = "mean_velocity"  # Campo de velocidad fijo

        if not self.layer:
            self.iface.messageBar().pushMessage(
                "EGMS", "Load a layer first", level=Qgis.Warning)
            return


        vmin = self.spin_min_vel.value()
        vmax = self.spin_max_vel.value()

        self.layer.setSubsetString(
            f'"{velocity_field}" >= {vmin} AND "{velocity_field}" <= {vmax}')

        self.iface.messageBar().pushMessage(
            "EGMS", f"Filter applied: {vmin} to {vmax} mm/yr", level=Qgis.Success)

    def draw_profile(self):
        print(f"egms_data in draw_profile: {len(self.egms_data)}")

        if not self.egms_data:
            self.iface.messageBar().pushMessage(
                "EGMS", "Load EGMS data first", level=Qgis.Warning)
            return

        velocity_field = "mean_velocity"

        line_layer = self.cmb_line_layer.currentLayer()
        if not line_layer:
            QMessageBox.warning(self, "EGMS",
                "Select a line layer for the profile trace.")
            return

        features = list(line_layer.selectedFeatures())
        if not features:
            features = list(line_layer.getFeatures())

        if not features:
            QMessageBox.warning(self, "EGMS", "The line layer is empty.")
            return

        line_geom = features[0].geometry()
        threshold = self.spin_threshold.value() / 111320

        profile_points = []
        # Iteramos sobre los puntos visibles de la capa (respetando el filtro)
        request = QgsFeatureRequest()
        request.setFilterExpression(self.layer.subsetString())
        for feature in self.layer.getFeatures(request):
            try:
                lat = feature['latitude']
                lon = feature['longitude']
                vel = feature['mean_velocity']
                
                if lat is None or lon is None or vel is None:
                    continue
                    
                lat = float(lat)
                lon = float(lon)
                vel = float(vel)
                
                pt = QgsPointXY(lon, lat)
                dist_squared = line_geom.closestSegmentWithContext(pt)[0]
                
                if dist_squared <= threshold ** 2:
                    along = line_geom.lineLocatePoint(
                        QgsGeometry.fromPointXY(pt))
                    profile_points.append((along, vel))
                    
            except (ValueError, KeyError, TypeError):
                continue

        if not profile_points:
            QMessageBox.warning(self, "EGMS",
                "No EGMS points found near the trace.\n"
                "Try increasing the distance threshold.")
            return

        profile_points.sort(key=lambda x: x[0])
        distances = [p[0] * 111320 for p in profile_points]
        velocities = [p[1] for p in profile_points]

        self.fig, ax = plt.subplots(figsize=(8, 4))
        colormap = self.cmb_colormap.currentText()
        point_size = self.spin_point_size.value()

        sc = ax.scatter(distances, velocities, c=velocities,
                        cmap=colormap, s=point_size, vmin=-20, vmax=20)

        ax.axhline(0, color='black', linewidth=0.5, linestyle='--')
        ax.set_xlabel("Distance (m)")
        ax.set_ylabel(f"{velocity_field} (mm/yr)")
        ax.set_title(f"EGMS Deformation Profile — Trace: {line_layer.name()}")

        plt.colorbar(sc, ax=ax, label="mm/yr")
        plt.tight_layout()
        plt.show()

        self.profile_data = list(zip(distances, velocities))

    def export(self):
        if self.fig is None or not self.profile_data:
            QMessageBox.warning(self, "EGMS", "Generate a profile first.")
            return

        folder = QFileDialog.getExistingDirectory(self, "Select export folder")
        if not folder:
            return

        png_path = os.path.join(folder, "egms_profile.png")
        self.fig.savefig(png_path, dpi=150)

        csv_path = os.path.join(folder, "egms_profile.csv")
        with open(csv_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(["distance_m", "velocity_mm_yr"])
            writer.writerows(self.profile_data)

        self.iface.messageBar().pushMessage(
            "EGMS", f"Exported to {folder}", level=Qgis.Success)